import color from "color";

import { Platform, Dimensions, PixelRatio } from "react-native";

const deviceHeight = Dimensions.get("window").height;
const deviceWidth = Dimensions.get("window").width;
const platform = Platform.OS;
const platformStyle = "material";
const isIphoneX =
  platform === "ios" && deviceHeight === 812 && deviceWidth === 375;

export default {
  platformStyle: "material",
  platform: "ios",
  androidRipple: true,
  androidRippleColor: "rgba(256, 256, 256, 0.3)",
  androidRippleColorDark: "rgba(0, 0, 0, 0.15)",
  btnUppercaseAndroidText: true,
  badgeBg: "#ED1727",
  badgeColor: "#fff",
  badgePadding: 3,
  btnFontFamily: "Roboto",
  btnDisabledBg: "#b5b5b5",
  buttonPadding: 6,
  btnPrimaryBg: "rgba(37,77,121,1)",
  btnPrimaryColor: "#fff",
  btnInfoBg: "rgba(62,202,99,1)",
  btnInfoColor: "#fff",
  btnSuccessBg: "rgba(62,202,99,1)",
  btnSuccessColor: "#fff",
  btnDangerBg: "#d9534f",
  btnDangerColor: "#fff",
  btnWarningBg: "#f0ad4e",
  btnWarningColor: "#fff",
  btnTextSize: 16.5,
  btnTextSizeLarge: 22.5,
  btnTextSizeSmall: 12,
  borderRadiusLarge: 57,
  iconSizeLarge: 45,
  iconSizeSmall: 18,
  cardDefaultBg: "#fff",
  cardBorderColor: "#ccc",
  CheckboxRadius: 0,
  CheckboxBorderWidth: 2,
  CheckboxPaddingLeft: 2,
  CheckboxPaddingBottom: 0,
  CheckboxIconSize: 18,
  CheckboxFontSize: 21,
  DefaultFontSize: 17,
  checkboxBgColor: "rgba(62,202,99,1)",
  checkboxSize: 20,
  checkboxTickColor: "#fff",
  brandPrimary: "rgba(37,77,121,1)",
  brandInfo: "#3F57D3",
  brandSuccess: "#5cb85c",
  brandDanger: "#d9534f",
  brandWarning: "#f0ad4e",
  brandDark: "#000",
  brandLight: "rgba(77,223,116,1)",
  fontFamily: "Roboto",
  fontSizeBase: 15,
  fontSizeH1: 27,
  fontSizeH2: 24,
  fontSizeH3: 21,
  footerHeight: 55,
  footerDefaultBg: "#3F51B5",
  footerPaddingBottom: 0,
  tabBarTextColor: "#fff",
  tabBarTextSize: 14,
  activeTab: "#fff",
  sTabBarActiveTextColor: "#007aff",
  tabBarActiveTextColor: "#fff",
  tabActiveBgColor: "rgba(37,77,121,1)",
  toolbarBtnColor: "#fff",
  toolbarDefaultBg: "rgba(37,77,121,1)",
  toolbarHeight: 65,
  toolbarSearchIconSize: 20,
  toolbarInputColor: "#fff",
  searchBarHeight: 30,
  searchBarInputHeight: 30,
  toolbarBtnTextColor: "#fff",
  toolbarDefaultBorder: "rgba(115,115,115,1)",
  iosStatusbar: "light-content",
  statusBarColor: "rgba(37,77,121,1)",
  darkenHeader: "#F0F0F0",
  iconFamily: "Ionicons",
  iconFontSize: 30,
  iconHeaderSize: 29,
  inputFontSize: 17,
  inputBorderColor: "rgba(37,77,121,1)",
  inputSuccessBorderColor: "rgba(62,202,99,1)",
  inputErrorBorderColor: "#ed2f2f",
  inputHeightBase: 50,
  inputColor: "#000",
  inputColorPlaceholder: "#575757",
  btnLineHeight: 19,
  lineHeightH1: 32,
  lineHeightH2: 27,
  lineHeightH3: 22,
  lineHeight: 20,
  listBg: "rgba(255,255,255,1)",
  listBorderColor: "#c9c9c9",
  listDividerBg: "#f4f4f4",
  listBtnUnderlayColor: "#DDD",
  listItemPadding: 10,
  listNoteColor: "#808080",
  listNoteSize: 13,
  defaultProgressColor: "#E4202D",
  inverseProgressColor: "#1A191B",
  radioBtnSize: 25,
  radioSelectedColorAndroid: "#5067FF",
  radioBtnLineHeight: 29,
  radioColor: "rgba(62,202,99,1)",
  segmentBackgroundColor: "#3F51B5",
  segmentActiveBackgroundColor: "#fff",
  segmentTextColor: "#fff",
  segmentActiveTextColor: "#3F51B5",
  segmentBorderColor: "#fff",
  segmentBorderColorMain: "#3F51B5",
  defaultSpinnerColor: "rgba(62,202,99,1)",
  inverseSpinnerColor: "#1A191B",
  tabDefaultBg: "#3F51B5",
  topTabBarTextColor: "#b3c7f9",
  topTabBarActiveTextColor: "#fff",
  topTabBarBorderColor: "#fff",
  topTabBarActiveBorderColor: "#fff",
  tabBgColor: "#F8F8F8",
  tabFontSize: 15,
  textColor: "#000",
  inverseTextColor: "#fff",
  noteFontSize: 14,
  defaultTextColor: "#000",
  titleFontfamily: "Roboto",
  titleFontSize: 19,
  subTitleFontSize: 14,
  subtitleColor: "#FFF",
  titleFontColor: "#FFF",
  borderRadiusBase: 2,
  borderWidth: 1,
  contentPadding: 10,
  dropdownLinkColor: "#414142",
  inputLineHeight: 24,
  deviceWidth: 2560,
  deviceHeight: 969,
  isIphoneX: false,
  inputGroupRoundedBorderRadius: 30,
};
